### ISSUE TITLE
Chiami la funzione 2 volte, potresti chiamarla una sola volta.

### ISSUE THREAD

**Issue by lionhard83** [Frank-345/risto-api#1]
https://github.com/Frank-345/risto-api/blob/b6d7649b32a35bc550f586e27c5bc3cd784744a8/routes/admin.js#L37

**Comment by lionhard83** [comment]
la funzione di cui parlo è `orders.deleteOrder`

**Comment by Frank-345** [comment]
grazie, risolto.
